---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rexkelly/portfolio
    - source /etc/profile
    - /usr/local/bin/npm ci --legacy-peer-deps 2>/dev/null || /usr/local/bin/npm install --legacy-peer-deps
    - /usr/local/bin/npm run build
